const students = [
    {
        id: 1,
        name: '강문일',
        number: '',
        cardImg: '/images/id1.png',
        letter: '',
    },
    {
        id: 2,
        name: '김민식',
        number: '',
        cardImg: '/images/id2.png',
        letter: '',
    },
    {
        id: 3,
        name: '배찬진',
        number: '',
        cardImg: '/images/id3.png',
        letter: '',
    },
    {
        id: 4,
        name: '송태민',
        number: '',
        cardImg: '/images/id4.png',
        letter: '',
    },
    {
        id: 5,
        name: '유도훈',
        number: '',
        cardImg: '/images/id5.png',
        letter: '',
    },
    {
        id: 6,
        name: '유성준',
        number: '',
        cardImg: '/images/id6.png',
        letter: '',
    },
    {
        id: 7,
        name: '윤주영',
        number: '',
        cardImg: '/images/id7.png',
        letter: '',
    },
    {
        id: 8,
        name: '이세령',
        number: '',
        cardImg: '/images/id8.png',
        letter: '',
    },
    {
        id: 9,
        name: '이윤빈',
        number: '',
        cardImg: '/images/id9.png',
        letter: '',
    },
    {
        id: 10,
        name: '정수호',
        number: '',
        cardImg: '/images/id10.png',
        letter: '',
    },
    {
        id: 11,
        name: '정예진',
        number: '',
        cardImg: '/images/id11.png',
        letter: '',
    },
    {
        id: 12,
        name: '채희수',
        number: '',
        cardImg: '/images/id12.png',
        letter: '',
    },
    {
        id: 13,
        name: '황일랑',
        number: '',
        cardImg: '/images/id13.png',
        letter: '',
    },
];

export default students;
